GOOGLE_API_KEY = 'AIzaSyA1l0qMOOelSTiTfWTF5dFxddhohHNEy0U'
GROQ_API_KEY = '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'
GOOGLE_API_KEY2 = "AIzaSyDP_ZS3FX_Ti6uK2n8jF2wuDCwgy9lo5oE"
GOOGLE_API_KEY3 = 'AIzaSyDiM9AZ-Ersdv5dHUNatudXKFJ4EUzrOWM'


